[package]
name = "bin-viewer"
version = "0.1.0"
authors = ["Alexander Vo <amv036@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
bitvec = "0.17.4"
